### ISSUE TITLE
Textadept 8.2 + DCD fails to start

### ISSUE THREAD

**Issue by whitebyte** [Hackerpilot/textadept-d#7]
When I put "dmd" folder into ~/.textadept/modules it stops working. I can't open any file and keep getting message: 

```
/home/anton/.textadept/modules/dmd/init.lua:355: table index is nil
```

**Comment by Hackerpilot** [comment]
Try it now.

**Comment by whitebyte** [comment]
Wow, that was fast! Fixed, thanks.
